Babc_logistic_core_identity/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Babc_logistic_core.Database;
using Babc_logistic_core.GIS.DTO;
using Babc_logistic_core.GIS.Model;
using Babc_logistic_core.Helpers;
using GDN.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace Babc_logistic_core.Controllers
{
    public class GoodsController : Controller
    {
        static log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        //OrderModel mOM;
        //CustomerModel mCM;
        //GenericTableModel mGTM;
        //BaseDataModel mBDM;
        private IMemoryCache _cache;
        private IConfiguration _Config;
        private UserManager<ApplicationUser> _userManager;


        public GoodsController(IConfiguration config, IMemoryCache cache, UserManager<ApplicationUser> userManager)
        {
            //mOM = new OrderModel(config, user);
            //mCM = new CustomerModel(config, user);
            //mGTM =  new GenericTableModel(config, user);
            //mBDM = new BaseDataModel(config, user);
            _Config = config;
            _userManager = userManager;

            _cache = cache;
        }

        // GET: Goods
        //[Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Index(string fsno)
        {
            List<GoodsViewModel> result = new List<GoodsViewModel>();

            try
            {
                OrderModel mOM = new OrderModel(_Config, _userManager.GetUserAsync(User)?.Result);

                Transport transport = mOM.GetTransportForDeliverNote(fsno);

                if(_cache.Get("delivernotes") != null)
                {
                    result = (List<GoodsViewModel>)_cache.Get("delivernotes");
                    //result = JsonConvert.DeserializeObject<List<GoodsViewModel>>(_cache.Get("delivernotes").ToString());
                }

                //if (HttpContext.Session.GetString("delivernotes") != null)
                //{

                //    result = JsonConvert.DeserializeObject<List<GoodsViewModel>>(HttpContext.Session.GetString("delivernotes"));
                //    //result = (List<GoodsViewModel>)Session["delivernotes"];
                //}

                if (!string.IsNullOrEmpty(transport?.DeliverNo))
                {
                    GoodsViewModel gvm = new GoodsViewModel();

                    gvm.DeliverNoteNo = transport.DeliverNo;
                    gvm.OrderNo = transport.OrderNo;
                    gvm.PackageCount = GeneralFunctions.getStrFromDecimal(transport.PackageAmount1 + transport.PackageAmount2 + transport.PackageAmount3);

                    result.Add(gvm);

                    _cache.Set("delivernotes", result);
                    //HttpContext.Session.SetString ("delivernotes", JsonConvert.SerializeObject(result));
                }
            }
            catch (Exception e)
            {
                logger.Error("Error in GoodsController.Index (POST)", e);
            }

            return View(result);
        }

        [Authorize]
        public ActionResult SubmitDeliver()
        {
            try
            {
                OrderModel mOM = new OrderModel(_Config, _userManager.GetUserAsync(User)?.Result);
                BaseDataModel mBDM = new BaseDataModel(_Config, _userManager.GetUserAsync(User)?.Result);
                GenericTableModel mGTM = new GenericTableModel(_Config, _userManager.GetUserAsync(User)?.Result);

                List<GoodsViewModel> deliverList = (List<GoodsViewModel>)_cache.Get("delivernotes");

                foreach (GoodsViewModel gvm in deliverList)
                {
                    OrderHead oh = mOM.GetOrderById(gvm.OrderNo, false);

                    // ** OM INTE BTEVILLKOR HAR V FLAGGA ***
                    BaseTable btPayment = mBDM.GetBaseTable("01", oh.PaymentTerms);

                    // Change invoice flag ONLY if paymentterms invoiceflag is NOT "V" and PickListState is NOT "F"
                    if (btPayment?.Code2.ToUpper().CompareTo("V") != 0 && oh.PickListState != "F")
                    {
                        UpdateTableIndexObject update = new UpdateTableIndexObject();

                        update.TableName = "HKA";
                        update.Key = gvm.DeliverNoteNo.PadRight(6) + "  1";
                        update.IndexFields = new List<FieldObject> { new FieldObject { FieldName = "HNR", FieldValue = gvm.DeliverNoteNo } };
                        update.Fields = new List<FieldObject> { new FieldObject { FieldName = "FAF", FieldValue = "1" } };

                        mGTM.UpdateTableByIndex(update, "false");
                    }

                    UpdateOrderRowTextZero(gvm.OrderNo, gvm.DeliverNoteNo);
                }

                _cache.Remove("delivernotes");
                //HttpContext.Session.Clear(); // Session["delivernotes"] = null;
            }
            catch (Exception e)
            {
                logger.Error("Error in GoodsController.SubmitDeliver()", e);
            }

            return Redirect("Index");
        }

        private void UpdateOrderRowTextZero(string orderNo, string fsno)
        {
            List<OrderRowText> orTextList = new List<OrderRowText>();

            try
            {
                OrderModel mOM = new OrderModel(_Config, _userManager.GetUserAsync(User)?.Result);
                CustomerModel mCM = new CustomerModel(_Config, _userManager.GetUserAsync(User)?.Result);

                OrderHead order = mOM.GetOrderById(orderNo, false);
                Customer customer = mCM.GetCustomerById(order.DeliverCustomerNo);

                OrderRowText orText = new OrderRowText();
                string date = System.DateTime.Today.ToString("yyMMdd");

                orText.OrderNo = orderNo;
                orText.DeliverNoteState = "1";
                //orText.InvoiceState = "0";
                orText.OrderConfirmationState = "1";
                orText.PickListState = "1";
                orText.RowNo = "0";
                orText.TextRowNo = "255";
                orText.Text = "Delivery note " + fsno + " was shipped " + date;

                if (string.IsNullOrEmpty(customer.UnifiedInvoice))
                {
                    orText.InvoiceState = "0";
                }

                orTextList.Add(orText);
                
                
                
                mOM.UpdateOrderRowTextList(orTextList);

            }
            catch (Exception e)
            {
                logger.Error("Error in GoodsController.UpdateOrderRowTextZero()", e);
            }
        }

        [Authorize]
        public ActionResult ClearSession()
        {
            try
            {
                HttpContext.Session.Clear(); //Session["delivernotes"] = null;
            }
            catch (Exception e)
            {
                logger.Error("Error in GoodsController.ClearSession()", e);
            }

            return Redirect("Index");
        }
    }
}

Babc_logistic_core_identity/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Babc_logistic_core.Database;
using Babc_logistic_core.GIS.DTO;
using Babc_logistic_core.GIS.Model;
using Babc_logistic_core.Helpers;
using Babc_logistic_core.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;
using Microsoft.VisualStudio.Web.CodeGeneration.Utils;
//using NuGet.Frameworks;

namespace Babc_logistic_core.Controllers
{
    public class OrderController : Controller
    {
        private static readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private string mGeneralIndexSearchCount = "0";
        private IConfiguration _Config;
        private UserManager<ApplicationUser> _userManager;
        
        public OrderController(IConfiguration config, UserManager<ApplicationUser> userManager)
        {
            try
            {
                _Config = config;
                _userManager = userManager;

            }
            catch (Exception)
            {
            }
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Index(string search_value, string search_type)
        {
            List<OrderHead> lst = new List<OrderHead>();

            OrderModel mOM = new OrderModel(_Config, _userManager.GetUserAsync(User)?.Result);

            if (string.IsNullOrEmpty(search_value))
            {
                return View();
            }

            if (search_type.Equals("Datum"))
            {
                lst = mOM.GetOrderByIdxList("1", "*", "LDT>=" + search_value, false, 20, true);
            }
            else if (search_type.Equals("Kund"))
            {
                lst = mOM.GetOrderByIdxList("2", search_value, "LEF<=4", false, 50, false);
            }
            else if (search_type.Equals("Säljarkod"))
            {
                lst = mOM.GetOrderByIdxList("4", search_value, "*", false, 50, false);
            }

            List<OrderHead> sortedList = lst.OrderByDescending(o => o.OrderNo).ToList();

            ViewBag.search_value = search_value;
            ViewBag.search_type = search_type;

            return View(sortedList);
        }

        [Authorize]
        public IActionResult PickList(string search_value, string search_value2, string search_type)
        {
            var user = _userManager.GetUserAsync(User)?.Result;

            OrderModel mOM = new OrderModel(_Config, user);
            BaseDataModel mBDM = new BaseDataModel(_Config, user);
            LogisticModel mLOM = new LogisticModel(_Config, user);

            List<OrderHead> lst = new List<OrderHead>();
            StringBuilder filter = new StringBuilder();
            List<OrderHead> tempLst = new List<OrderHead>();
            List<string> additionalLst = new List<string>();
            List<string> checkLst = new List<string>();

            PickListParam olp = new PickListParam();
            OrderHead ohda = new OrderHead();

            // When landing on the page the first time
            if (string.IsNullOrEmpty(search_type))
                return View();

            if (search_type.Equals("supplie"))
            {
                try
                {
                    List<FilterDTO> filterList = getFilterList("FILTERS");
                    olp.Filter = parseFilterConstants(filterList[0].Filter);

                    if (filterList[0].UseCache == true)
                    {
                        olp.Cache = new CacheParam { CacheId = user.GisToken + "_supplie", ReadFrom = true, UpdateTo = false, CheckConsistency = true };
                    }
                }
                catch (Exception e)
                {
                    logger.Error("Error setting filter", e);
                }
            }
            else if (search_type.Equals("pre"))
            {
                try
                {
                    List<FilterDTO> filterList = getFilterList("FILTERO");
                    olp.Filter = parseFilterConstants(filterList[0].Filter);

                    if (filterList[0].UseCache == true)
                    {
                        olp.Cache = new CacheParam { CacheId = user.GisToken + "_pre", ReadFrom = true, UpdateTo = false };
                    }
                }
                catch (Exception e)
                {
                    logger.Error("Error setting filter", e);
                }
            }
            else if (search_type.Equals("other"))
            {
                try
                {
                    List<FilterDTO> filterList = getFilterList("FILTERD");
                    olp.Filter = parseFilterConstants(filterList[0].Filter);

                    if (filterList[0].UseCache == true)
                    {
                        olp.Cache = new CacheParam { CacheId = user.GisToken + "_other", ReadFrom = true, UpdateTo = false };
                    }
                }
                catch (Exception e)
                {
                    logger.Error("Error setting filter", e);
                }
            }

            olp.Index = 1;
            olp.IndexFilter = "*";
            olp.IndexCount = int.Parse(mGeneralIndexSearchCount);
            olp.OrderSerie = "A";
            olp.IncludeDeliveredRows = false;
            olp.WithRows = true;
            olp.MaxCount = 100;
            olp.ReverseReading = true;
            olp.IncludeProduct = true;

            try
            {
                List<FilterDTO> filterList = getFilterList("FILTERA");
                olp.AdditionalFilter = parseFilterConstants(filterList[0].Filter);
            }
            catch (Exception e)
            {
                logger.Error("Error setting filter", e);
            }

            List<OrderHead> temp = new List<OrderHead>();

            // Additionlorders or ordinary search
            if (search_type.Equals("customer"))
            {
                olp.Index = 2;
                olp.IndexFilter = search_value.PadRight(10) + ";" + search_value.PadRight(10);
                //olp.IndexFilter = search_value;
                olp.Filter = olp.AdditionalFilter;
                olp.IndexCount = 0;

                lst = mLOM.GetOrderListWithAdditionalOrder(olp);

                // Mafi unique, filter out order depening on next deliverdate
                List<OrderHead> tempAdditional = new List<OrderHead>();
                foreach (OrderHead oh in lst)
                {
                   

                    if (oh.OrderRows.Count > 0)
                    {
                        OrderRow orDelDate = oh.OrderRows.Where(f => f.DeliverState != "5").OrderBy(r => r.PreferedDeliverDate)?.First();

                        if (orDelDate != null)
                        {
                            if (orDelDate.OrderNo.Trim() == oh.OrderNo.Trim())
                            {
                                oh.PreferedDeliverDate = orDelDate.PreferedDeliverDate;             //Skall vi ändra datumformat igen?
                            }
                        }
                    }

                    // search_value 2 == original orders PreferedDeliverDate
                    if (oh.PreferedDeliverDate == search_value2)
                    {
                        temp.Add(oh);
                    }
                }
            }
            else
            {
                lst = mLOM.GetOrderListWithAdditionalOrder(olp);
                BaseTable btWH = mBDM.GetBaseTable("WELOGG", "WH");
                if (lst != null)
                {
                    foreach (OrderHead oh in lst)
                    {
                        if (oh.OrderNo == "144328")
                        {
                            Console.WriteLine();

                        }
                        // Mark order that has materialplanned rows
                        oh.HasMaterialPlannedRows = (oh.OrderRows.Where(r => r.MTF.CompareTo("0") > 0)?.ToList().Count > 0);

                        oh.IsWholeOrderDeliverable = true;
                        oh.NonDeliverableRows = 0;

                        try
                        {
                            oh.OrderRows.RemoveAll(r => string.IsNullOrEmpty(r.ProductNo));
                        }
                        catch (Exception e)
                        {
                            logger.Debug("Error : " + e.Message);
                        }

                        decimal amountTvk = 0;
                        foreach (OrderRow or in oh.OrderRows)
                        {


                            if (btWH?.Id == "WH")
                            {
                                if (btWH.Code1 == "T") // Warehouse accoring to Description is mandatory
                                {
                                    // If OR warehouse not match madatory warehouse from settings
                                    if (or.WarehouseNo.Trim() != btWH.Description.Trim())
                                    {
                                        oh.NonDeliverableRows++;
                                        oh.IsWholeOrderDeliverable = false;

                                    }
                                    // If warehouse not have enough amount to supplie this row

Babc_logistic_core_identity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0" />*@
    <title>@ViewData["Title"] - BABC_Logistics_core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/waitMe.css" />
    <link rel="stylesheet" href="~/css/bootstrap-table-expandable.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/dist/signature_pad.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script src="~/js/spinner.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/fd9835abc2.js" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/ta_package_selector.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/black-tie/jquery-ui.css">


    @RenderSection("Scripts", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" id="main-menu">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">

                            <a class="nav-link text-light" asp-controller="Order" asp-route-search_type="supplie" asp-action="PickList" asp-route-search_value="@DateTime.Now.ToString("yyMMdd")">Customer Order</a>

                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Order" asp-action="Picklist">Picklist</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Order" asp-action="GetStartedOrderList">Ongoing orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Production" asp-action="MaterialOrderPickList">Material orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Goods" asp-action="Index">Confirm delivery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="FloatingStockLocation" asp-action="Inventory">Inventory</a>
                        </li>
           @*             <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="InventorySet" asp-action="Index">Inventory sets</a>
                        </li>*@
                        <li class="nav-item">

                            <a class="nav-link text-light" asp-controller="OrderOverView" asp-route-search_type="supplie" asp-action="PickList" asp-route-search_value="@DateTime.Now.ToString("yyMMdd")">OrderOverView</a>

                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="ProductionOverView" asp-action="ProductionOverview">ProductionOverview</a>
                            </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Purchase" asp-action="PickList">@Babc_logistic_core.Language.Resources.PurchaseMenu</a>
                            </li>*@
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="LogtradeMapping">@Babc_logistic_core.Language.Resources.Admin</a>
                            </li>*@
                    </ul>
                </div>
                <div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Babc_logistic_core_identity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/spinner.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

        @RenderSection("Scripts", required: false)*@
</body>
</html>

Babc_logistic_core_identity/Views/Shared/_LayoutOverView.cshtml
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Babc_logistic_core_identity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>
<body>
  

    <div class="">
        <main role="main">
            @RenderBody()
        </main>
    </div>

 @*   <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Babc_logistic_core_identity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</body>
</html>