Babc_logistic_core_identity/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Babc_logistic_core.Database;
using Babc_logistic_core.GIS.DTO;
using Babc_logistic_core.GIS.Model;
using Babc_logistic_core.Helpers;
using Babc_logistic_core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace Babc_logistic_core.Controllers
{
    public class InventoryController : Controller
    {
        static log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private readonly InventoryContext _context;

        //private GIS.Model.ProductModel mPM;
        private IConfiguration _Config;
        private UserManager<ApplicationUser> _userManager;

        public InventoryController(IConfiguration config, InventoryContext context, UserManager<ApplicationUser> userManager)
        {
            //mPM = new GIS.Model.ProductModel(config, user);
            _Config = config;
            _userManager = userManager;

            _context = context;
        }

        // GET: Inventory
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult OverView()
        {
            InventoryOverviewVM result = new InventoryOverviewVM();

            try
            {
                result.ProductNo = "";
                result.Warehouse = "";
                result.InventorySetList = new List<InventorySet>();

                result.InventorySetList.Add(new InventorySet { ID = 1, Description = "Lista 1" });
                result.InventorySetList.Add(new InventorySet { ID = 2, Description = "Lista 2" });
                result.InventorySetList.Add(new InventorySet { ID = 3, Description = "Lista 3" });
                result.InventorySetList.Add(new InventorySet { ID = 4, Description = "Lista 4" });
                result.InventorySetList.Add(new InventorySet { ID = 5, Description = "Lista 5" });
            }
            catch (Exception e)
            {

            }

            return View(result);
        }

        [Authorize]
        public IActionResult CreateInventorySet(CreateInventorySetVM param)
        {
            CreateInventorySetVM result = new CreateInventorySetVM();

            try
            {
                if(!string.IsNullOrEmpty(param.WarehousNo))
                {
                    result.Result = new InventorySet();
                    result.Description = param.Description;

                    //List<Product> prodList = mPM.GetProductList("1", "*", "FRY!=z");

                    //foreach(Product product in prodList)
                    //{
                    //    WarehouseNumber wn = product.WarehouseList.Find(w => w.Id == param.WarehousNo);
                    //    if((wn != null))
                    //    {
                    //        result.Result.CreatedDate = DateTime.Now;
                    //        result.Result.ID = 0;
                    //        result.Result.InventoryList = new List<Inventory>();

                    //        Inventory inv = new Inventory();
                    //        inv.Date = GeneralFunctions.getStrFromDate(DateTime.Now);
                    //        inv.OriginalAmount = wn.Stock;
                    //        inv.InventoryDone = false;
                    //        inv.ProductNo = product.ProductNo;
                    //        inv.VIPAtTime = GeneralFunctions.getDecimalFromStr(wn.VIP);
                    //        inv.WarehouseNo = wn.Id;

                    //        result.Result.InventoryList.Add(inv);
                    //    }
                    //}

                    InventorySet addedSet = InventoryLib.AddInventorySet(result.Result);

                }
            }
            catch (Exception e)
            {

            }

            return View(result);

        }

        [HttpPost]
        [Authorize]
        public IActionResult OverView(InventoryOverviewVM param)
        {
            InventoryOverviewVM result = param;
   
            try
            {
                result.CurrentInventorySet = InventoryLib.GetInventorySet(param.CurrentInventorySetId);
             
                }
            catch (Exception e)
            {
                logger.Error("Error in OverView [POST]", e);
            }

            return View(result);
        }


        [Authorize]
        public string ReadBackup(string filename)
        {
            List<InventoryDetail> lst = new List<InventoryDetail>();
            string result = "";

            try
            {
                //using (StreamReader _testData = new StreamReader(Server.MapPath("~/" + filename), true))
                //{
                //    string json = _testData.ReadToEnd();

                //    lst = JsonConvert.DeserializeObject<List<InventoryDetail>>(json);

                //    Cache.DataCache.AddToCache<List<InventoryDetail>>("inventory", 10, lst);
                //}
            }
            catch (Exception e)
            {
                result = e.Message;
            }

            return result;
        }

        [Authorize]
        public string FindProduct(string search)
        {
            Product result = new Product();

            try
            {
                GIS.Model.ProductModel mPM = new GIS.Model.ProductModel(_Config, _userManager.GetUserAsync(User)?.Result);

                var p = mPM.GetProductById(search);

                if (p?.ProductNo != null)
                {
                    result = p;
                }
                else
                {
                    result = new Product { ProductNo = null, Description = "" };
                }
            }
            catch (Exception e)
            {

            }

            return JsonConvert.SerializeObject(result);
        }

        [Authorize]
        public IActionResult SumInventory()
        {
            List<InventorySumVM> result = new List<InventorySumVM>();

            try
            {
                //List<InventoryDetail> lst = Cache.DataCache.GetFromCache<InventoryDetail>("inventory");
                //var groupedList = lst.GroupBy(inventory => inventory.ProductNo);

                //foreach (var group in groupedList)
                //{
                //    InventorySumVM sum = new InventorySumVM();

                //    sum.Amount = group.Sum(s => s.Amount);
                //    sum.ProductNo = group.Key;
                //    sum.Warehouse = group.First().WarehouseNo;
                //    sum.InventoryDate = group.Last().Date;

                //    sum.ContainingInventories = group.ToList();

                //    result.Add(sum);
                //}
            }
            catch (Exception e)
            {

            }

            return View(result);
        }

        [Authorize]
        public System.Web.Mvc.FileContentResult ExecuteInventory(int setid)
        {
            InventoryFileResult result = new InventoryFileResult();

            try
            {
                GIS.Model.ProductModel mPM = new GIS.Model.ProductModel(_Config, _userManager.GetUserAsync(User)?.Result);

                var inventorys = InventoryLib.GetAllInventorOnSet(setid);

                InventoryFileParam inventory = new InventoryFileParam();
                foreach (var sum in inventorys)
                {
                    inventory.Inventorys.Add(new InventoryParam
                    {
                        ProductNo = sum.ProductNo,
                        WarehouseNo = sum.WarehouseNo,
                        Amount = sum.Amount,
                        Date = sum.Date,
                        Time = sum.Time,
                        PlaceName = "",
                        PlaceNo = "",
                        Note = sum.Note,
                        User = "GIS",
                        Terminal = "G1",
                        Rating = "",
                    });
                }

                result = mPM.CreateInventoryFile(inventory);
            }
            catch (Exception e)
            {
                logger.Error("Error in ExecuteInventory", e);
            }

            byte[] byteArr = Encoding.UTF8.GetBytes(result.InventoryFile);
            string mimeType = "text/plain";

            return new System.Web.Mvc.FileContentResult(byteArr, mimeType)
            {
                FileDownloadName = "excelfromByte1.xlsx"
            };
           
        }

        [Authorize]
        public string Delete(string id)
        {
            string result = "";

            try
            {
                //List<InventoryParam> lst = Cache.DataCache.GetFromCache<InventoryParam>("inventory");

                //var itemToRemove = lst.Where(i => i.Note == id).FirstOrDefault();

                //if (itemToRemove != null)
                //{
                //    lst.Remove(itemToRemove);
                //}

                //Cache.DataCache.AddToCache<List<InventoryParam>>("inventory", 10, lst);
            }
            catch (Exception e)
            {
                result = "false";
            }

            return result;
        }

        private Tuple<bool, string> CheckWarehouse(Product product, InventoryOverviewVM param)
        {
            Tuple<bool, string> result = new Tuple<bool, string>(false, "");

            //checked inventory on product if pressent

Babc_logistic_core_identity/Views/Inventory/CreateInventorySet.cshtml
@model Babc_logistic_core.Models.CreateInventorySetVM
@{
    ViewData["Title"] = "CreateInventorySet";
}

<h1>CreateInventorySet</h1>
<form asp-controller="Inventory" asp-action="CreateInventorySet" method="post" class="form-horizontal" role="form">
    <input asp-for="Description" />
    <input asp-for="WarehousNo" />
    <button type="submit">Create</button>
</form>
@*@using (Html.BeginForm("CreateInventorySet", "Inventory", null, FormMethod.Post, false, null))
{
    <div style="margin-top:30px;">
        <div class="form-group">
            <label>Lagernr</label>
            <input type="text" class="form-control" id="warehouseno" name="WarehousNo" tabindex="-1" placeholder="Lagernr" onsubmit="required()" value="">
        </div>
        <div class="form-group">
            <label>ID</label>
            <input type="text" class="form-control" id="Id" name="Id" tabindex="-1" placeholder="Lagernr" value="">
        </div>
        <div class="form-group">
            <label for="productno">Artikel</label>
            <input type="text" class="form-control" id="Description" name="Description" placeholder="">
        </div>
        <button type="submit" id="submit" class="btn btn-primary" style="margin-top:10px">Submit</button>

    </div>
}*@

<div>
    @if (Model.Result != null)
    {
        <table class="table">
            <tr>
                <th>
                    Artikel
                </th>
                <th>
                    Lagernr
                </th>
                <th>
                    Inventerat antal
                </th>
                <th>
                    Datum
                </th>
                <th>
                    Tidpunkt
                </th>
                <th></th>
            </tr>

            @if (Model != null)
            {
                foreach (var item in Model.Result?.InventoryList)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductNo, new { @id = "productno" })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WarehouseNo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Time)
                        </td>
                        <td>
                            <a class="delete">Delete</a><br>
                        </td>
                    </tr>
                }
            }
        </table>
    }


</div>


Babc_logistic_core_identity/Views/Inventory/ExecuteInventory.cshtml
@model IEnumerable<Babc_logistic_core.GIS.DTO.InventoryResult>

@{
    ViewBag.Title = "ExecuteInventory";
}

<h2>Inventeringsresultat</h2>
<div style="margin-top:30px;margin-bottom:10px">
    @Html.ActionLink("Till startsidan", "OverView", "Inventory", new { @class = "btn btn-primary" })
</div>
<table class="table">
    <tr>
        <th>
            Artikel
        </th>
        <th>
            Lagernr
        </th>
        <th>
            Datum
        </th>
        <th>
            Tidpunkt
        </th>
        <th>
            Gammalt antal
        </th>
        <th>
            Inventerat antal
        </th>
        <th>
            Meddelande
        </th>
        <th>
            Status
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WarehouseNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OldAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InternalMoveMessage)
            </td>
            <td>
                @if (item.Succeeded)
                {
                    <span class="badge bg-success">Success</span>
                }
                else
                {
                    <span class="badge bg-danger">Success</span>
                }

            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>*@
        </tr>
    }

</table>

Babc_logistic_core_identity/Views/Inventory/OverView.cshtml
@model Babc_logistic_core.Models.InventoryOverviewVM
@{
    ViewBag.Title = "OverView";
}

<h2>Inventering</h2>
<div style="background-color:lightgray" id="Border">
    <form asp-controller="Inventory" asp-action="Overview" method="post" class="form-horizontal" role="form">
        <div class="form-group">
            <div class="row">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    <label asp-for="CurrentInventorySetId" class="control-label"></label>
                    <select asp-for="CurrentInventorySetId"
                            class="form-control"
                            asp-items="@(new SelectList(Model.InventorySetList,"ID", "Description"))">
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    <input id="Submit1" type="submit" value="submit" />
                </div>
            </div>
        </div>
    </form>
    <form method="post">
        <button asp-controller="Inventory" asp-action="CreateInventorySet">Create new Set</button>
    </form>
</div>
<div id="inventory-header" class="input-group" style="width:200px">

    @using (Html.BeginForm("OverView", "Inventory", null, FormMethod.Post, false, new { @onsubmit = "return validateForm()", @name = "myForm" }))
    {
        <div class="">
            <div class="form-group">
                <label>Lagernummer</label>
                <input type="text" class="form-control" id="warehouse" name="Warehouse" tabindex="-1" placeholder="Lagernr" onsubmit="required()" value="@Model.Warehouse">
                <small id="warehouse-warning" class="form-text" style="color:red">@Model.Message</small>
            </div>
            <div class="form-group">
                <label for="productno">Artikel</label>
                <input type="text" class="form-control" id="productno" name="ProductNo" placeholder="Ange artikelnummer">
                <small id="product-description" class="form-text text-muted"></small>
            </div>
            <div class="form-group">
                <label for="amount">Antal</label>
                <input type="number" class="form-control" id="amount" name="Amount" placeholder="Antal">
            </div>
            <button type="submit" id="submit" class="btn btn-primary" style="margin-top:10px">Submit</button>

        </div>
    }

    <a href="CreateInventorySet" class="btn btn-primary">Create</a>

    @*@using (Ajax.BeginForm("UpdateFilter", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "divEmp" }))
        {
            <form>
                <div class="form-group">
                    <label for="productno">Artikel</label>
                    <input type="text" class="form-control" id="productno" aria-describedby="emailHelp" placeholder="Ange artikelnummer">
                </div>
                <div class="form-group">
                    <label for="amount">Antal</label>
                    <input type="number" class="form-control" id="amount" placeholder="Antal">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        }*@
</div>
<div>
    @*@{

            Html.RenderPartial("_InventoryListView", Model == null ? null : Model.InventorySetList);
        }*@

</div>


<script type='text/javascript'>
    $(document).ready(function () {
        alert("");
        // Put focus on product field on load
        if ($('#warehouse').val() == "") {
            $('#warehouse').focus();
        }
        else {
            $('#productno').focus();
        }

        @*// Handle ajax event to check that product exist before moving on
        $('#productno').blur(function () {
            if ($('#productno').text != "") {
                $.ajax({
                    url: "@Url.Action("FindProduct","Inventory")",
                    data: {search: $('#productno').val()},
                    dataType: "json",
                    success: function (model) {
                        if (model.ProductNo != null) {
                            $('#product-description').text(model.Description);
                        }
                        else {
                            $('#product-description').text('Artikeln hittades ej!!');
                            $('#productno').focus();
                            $('#productno').val("");
                        }

                    },
                    error: function (result) {
                        alert('error');
                    }
                });
            }

        });*@
    });

    function validateForm() {
        var x = document.forms["myForm"]["Warehouse"].value;
        if (x == "") {
            alert("Lagernr måste anges");
            $('#warehouse').focus();
            return false;
        }
    }




</script>

Babc_logistic_core_identity/Views/Inventory/SumInventory.cshtml
@model IEnumerable<Babc_logistic_core.Models.InventorySumVM>

@{
    ViewBag.Title = "Summerad inventering";
}


<h2>Summerad inventering per artikel</h2>

<p>
    <div style="margin-top:30px;margin-bottom:10px">
        @Html.ActionLink("Till startsidan", "OverView", "Inventory", new { @class = "btn btn-primary" })
        @Html.ActionLink("Genomför inventering", "ExecuteInventory", "Inventory", new { @class = "btn btn-primary" })
    </div>
</p>
<table class="table">
    <tr>
        <th>
            Artikelnr
        </th>
        <th>
            Lagernr
        </th>
        <th>
            Inventerat antal
        </th>
        @*<th></th>*@
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Warehouse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>*@
        </tr>
    }

</table>

Babc_logistic_core_identity/Views/Inventory/_InventoryListView.cshtml
@model IEnumerable<Babc_logistic_core.Models.InventoryDetail>


<div style="margin-top:30px;margin-bottom:10px">
    @Html.ActionLink("Summera lista på produkt", "SumInventory", "Inventory", new { @class = "btn btn-primary" })
</div>
<table class="table">
    <tr>
        <th>
            Artikel
        </th>
        <th>
            Lagernr
        </th>
        <th>
            Inventerat antal
        </th>
        <th>
            Datum
        </th>
        <th>
            Tidpunkt
        </th>
        <th></th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr class="@item.Note">
                <td>
                    @Html.DisplayFor(modelItem => item.ProductNo, new { @id = "productno" })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WarehouseNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Time)
                </td>
                <td>
                    <a id="@item.Note" class="delete">Delete</a><br>
                </td>
            </tr>
        }
    }
</table>

<script type='text/javascript'>
    $(function(){
          //When the blur event occurs from your Textbox (you lose focus)
        $(document).on('click', '.delete', function( e ){
            var id = this.id;
            $.ajax({
                url: "@Url.Action("Delete","Inventory")",
                data: { id: id },
                     dataType: "text",
                success: function (model) {
                    $("tr").remove("." + id);
                },
                error: function (result) {
                        alert("bad");
                }
              });
          });
    });

</script>